# Nav
menu:
  home: /
  about: /about
  archives: /archives
  tags: /tags
  # categories: /categories

# Read More text
excerpt_link: "Keep Reading..."

# Google Analytics Tracking ID
# Replace 'false' with your ID to enable
google_analytics: false

# Share links
show_share_links: true
twitter_handle: jlincolndennis

# Comments
disqus_shortname: jlincolndennis
